version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3.9.14-management
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    build: ./
    command: node ./bin/www
    networks:
      - app-network
    ports:
      - 8080:3000
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://user:password@rabbitmq:5672
    restart: on-failure

networks:
  app-network:
    driver: bridge